FROM maven as builder
COPY apps/service/pom.xml /work/pom.xml
RUN cd /work; mvn -B dependency:go-offline 
COPY apps/service/src /work/src
RUN  cd /work; mvn clean install
FROM openjdk:11
COPY --from=builder /work/target/app.jar /opt/app/app.jar
ENTRYPOINT [ "java", "-jar", "/opt/app/app.jar" ]
